version: "3.9"

services:
  web:
    build: ./web
    container_name: chw_blogger_web
    ports:
      - "8080:80"
      - "2222:22"
    environment:
      WP_DB_HOST: db
      WP_DB_NAME: wordpress
      WP_DB_USER: root
      WP_DB_PASS: sup3r_s3cr3t
      WP_SITE_URL: http://blogger.chw:8080/assets/fonts/blog
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/wordpress
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: chw_blogger_db
    environment:
      MYSQL_ROOT_PASSWORD: sup3r_s3cr3t
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  wp_data:
  db_data:
